name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: umbrella
  color: blue

# Define your inputs here.
inputs:
  github-token:
    description:
      'Set the GitHub token to have the action comment the natspec smells
      summary in the pull request. This token is provided by Actions, you do not
      need to create your own token. Optional. Default: ``'
  working-directory:
    description:
      'The working directory containing the source files referenced in the
      natspec-smells config file. Optional. Default: `./`'
  update-comment:
    description:
      'Set to `true` to update the previous natspec smells comment if such
      exists. When set to `false`, a new comment is always created. Optional.
      Default: `false`'
    required: false
    default: 'false'

# Define your outputs here.
outputs:
  total-smells:
    description: 'The total smells founds by natspec-smells.'

runs:
  using: 'node20'
  main: 'dist/index.js'
