name: 'Solidity Natspec Smells'
description: 'Report Solidity natspec-smells findings as a PR comment'
author: 'RA2 Tech'

branding:
  icon: book
  color: blue

inputs:
  github-token:
    description:
      'Set the GitHub token to have the action comment the natspec smells
      summary in the pull request. This token is provided by Actions, you do not
      need to create your own token. Optional. Default: ``'
  working-directory:
    description:
      'The working directory containing the source files referenced in the
      natspec-smells config file. Optional. Default: `./`'
  update-comment:
    description:
      'Set to `true` to update the previous natspec smells comment if such
      exists. When set to `false`, a new comment is always created. Optional.
      Default: `false`'
    required: false
    default: 'false'

outputs:
  total-smells:
    description: 'The total smells founds by natspec-smells.'

runs:
  using: 'node20'
  main: 'dist/index.js'
