name: Natspec Example

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  natspec-smells:
    name: Test natspec-smells
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        id: checkout
        with:
          submodules: recursive

      - name: Install Node 20
        uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version: 20

      - name: Test Local Action
        uses: ./
        id: test-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: fileExample
          update-comment: true
