name: Natspec Example

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  natspec-smells:
    name: Test natspec-smells
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: fileExample
          update-comment: true
